### ISSUE TITLE
Admin metadata in Sword2 METS

### ISSUE THREAD

**Issue by tomwrobel** [tomwrobel/ora_data_model#68]
Once a record is created, updates to fields such as record_first_reviewed_by and record_first_reviewed_time are not visible in the METS file: these may need to be crosswalked into and from Hyrax.

I haven't tried to input these fields directly into Hyrax, to see if they crosswalk in.

@anusharanganathan I seem to recall that you had some updates planned to the admininstrative metadata crosswalks. Do I remember correctly?

**Comment by tomwrobel** [comment]
Hi @anusharanganathan, bumping after yesterday's discussion!

**Comment by tomwrobel** [comment]
```
terms:
  - id: Third-party copyright (access exception)
    term: Third-party copyright (access exception)
    xwalk: Access1
  - id: Publisher embargo too long (access exception)
    term: Publisher embargo too long (access exception)
    xwalk: Access2
  - id: No green or gold OA allowed by the publication (access exception)
    term: No green or gold OA allowed by the publication (access exception)
    xwalk: Access3
  - id: Unable to secure a compliant version for deposit, e.g. not lead author (deposit exception)
    term: Unable to secure a compliant version for deposit, e.g. not lead author (deposit exception)
    xwalk: Deposit2
  - id: Author not employed by a UK HEI at the time of submission for publication (deposit exception)
    term: Author not employed by a UK HEI at the time of submission for publication (deposit exception)
    xwalk: Deposit3
  - id: Published 'gold' open access
    term: Published 'gold' open access
    xwalk: Deposit6
  - id: Not deposited in 3 months of acceptance, but within three months of publication (deposit exception)
    term: Not deposited in 3 months of acceptance, but within three months of publication (deposit exception)
    xwalk: Deposit7
  - id: Repository short-term technical failure (technical exception)
    term: Repository short-term technical failure (technical exception)
    xwalk: Tech3
  - id: Other exception
    term: Other exception
    xwalk: Other
```
